version: '3.8'

services:
  app:
    build: 
      context: ./app
    container_name: backend_app
    env_file: .env
    command: >
      bash -c "python -m src.main"
    networks:
      - fast_api_telegram_network
    restart: always
    depends_on:
      - postgresql
  
  postgresql:
    image: postgres:16-bookworm
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - fast_api_telegram_network
    restart: always
    shm_size: 128mb


volumes:
  postgres_data:

networks:
  fast_api_telegram_network:
    driver: bridge
