version: "3.9"

services:
  app:
    build:
      context: app
      dockerfile: src/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
