"""altr_passwd_type

Revision ID: 9430d0ab17f9
Revises: 9de62062daf4
Create Date: 2025-01-31 15:45:47.256929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9430d0ab17f9'
down_revision: Union[str, None] = '9de62062daf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.LargeBinary(length=60),
                    existing_nullable=True,
                    postgresql_using='password::bytea'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
                    existing_type=sa.LargeBinary(length=60),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=True,
                    postgresql_using='password::text'
                    )
    # ### end Alembic commands ###
