"""fixTUname_typo

Revision ID: 9de62062daf4
Revises: 34e344d741c1
Create Date: 2025-01-27 13:37:38.611315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de62062daf4'
down_revision: Union[str, None] = '34e344d741c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_username', sa.String(length=32), nullable=True))
    op.drop_constraint('users_tlegram_username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['telegram_username'])
    op.drop_column('users', 'tlegram_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tlegram_username', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_tlegram_username_key', 'users', ['tlegram_username'])
    op.drop_column('users', 'telegram_username')
    # ### end Alembic commands ###
